// Generated by svd2swift.

import MMIO

/// Analog to Digital Converter
public let adc = ADC(unsafeAddress: 0x4001_2400)

/// EXTI address block description
public let exti = EXTI(unsafeAddress: 0x4002_1800)

/// GPIOA address block description
public let gpioa = GPIO(unsafeAddress: 0x5000_0000)

/// GPIOB address block description
public let gpiob = GPIO(unsafeAddress: 0x5000_0400)

/// I2C register block
public let i2c = I2C(unsafeAddress: 0x4000_5400)

/// RCC address block description
public let rcc = RCC(unsafeAddress: 0x4002_1000)

/// SYSCFG register block
public let syscfg = SYSCFG(unsafeAddress: 0x4001_0000)
