// Generated by svd2swift.

import MMIO

/// IWDG register block
@RegisterBlock
public struct IWDG: Sendable {
    /// IWDG key register
    @RegisterBlock(offset: 0x0)
    public var kr: Register<KR>

    /// IWDG prescaler register
    @RegisterBlock(offset: 0x4)
    public var pr: Register<PR>

    /// IWDG reload register
    @RegisterBlock(offset: 0x8)
    public var rlr: Register<RLR>

    /// IWDG status register
    @RegisterBlock(offset: 0xc)
    public var sr: Register<SR>

    /// IWDG window register
    @RegisterBlock(offset: 0x10)
    public var winr: Register<WINR>
}

extension IWDG {
    /// IWDG key register
    @Register(bitWidth: 32)
    public struct KR {
        /// Writing the key value 0xCCCC starts the watchdog (except if the hardware watchdog option is selected)
        @WriteOnly(bits: 0..<16)
        public var key: KEY
    }

    /// IWDG prescaler register
    @Register(bitWidth: 32)
    public struct PR {
        /// Note: Reading this register returns the prescaler value from the VDD voltage domain. This value may not be up to date/valid if a write operation to this register is ongoing. For this reason the value read from this register is valid only when the PVU bit in the status register (IWDG_SR) is reset.
        @ReadWrite(bits: 0..<3)
        public var pr_field: PR_FIELD
    }

    /// IWDG reload register
    @Register(bitWidth: 32)
    public struct RLR {
        /// Note: Reading this register returns the reload value from the VDD voltage domain. This value may not be up to date/valid if a write operation to this register is ongoing on it. For this reason the value read from this register is valid only when the RVU bit in the status register (IWDG_SR) is reset.
        @ReadWrite(bits: 0..<12)
        public var rl: RL
    }

    /// IWDG status register
    @Register(bitWidth: 32)
    public struct SR {
        /// Prescaler value can be updated only when PVU bit is reset.
        @ReadOnly(bits: 0..<1)
        public var pvu: PVU

        /// Reload value can be updated only when RVU bit is reset.
        @ReadOnly(bits: 1..<2)
        public var rvu: RVU

        /// Window value can be updated only when WVU bit is reset.
        @ReadOnly(bits: 2..<3)
        public var wvu: WVU
    }

    /// IWDG window register
    @Register(bitWidth: 32)
    public struct WINR {
        /// Note: Reading this register returns the reload value from the VDD voltage domain. This value may not be valid if a write operation to this register is ongoing. For this reason the value read from this register is valid only when the WVU bit in the (IWDG_SR) is reset.
        @ReadWrite(bits: 0..<12)
        public var win: WIN
    }
}
