// Generated by svd2swift.

import MMIO

/// Serial peripheral interface
@RegisterBlock
public struct SPI: Sendable {
    /// SPI control register 1
    @RegisterBlock(offset: 0x0)
    public var cr1: Register<CR1>

    /// SPI control register 2
    @RegisterBlock(offset: 0x4)
    public var cr2: Register<CR2>

    /// SPI status register
    @RegisterBlock(offset: 0x8)
    public var sr: Register<SR>

    /// SPI data register
    @RegisterBlock(offset: 0xc)
    public var dr: Register<DR>

    /// SPI CRC polynomial register
    @RegisterBlock(offset: 0x10)
    public var crcpr: Register<CRCPR>

    /// SPI Rx CRC register
    @RegisterBlock(offset: 0x14)
    public var rxcrcr: Register<RXCRCR>

    /// SPI Tx CRC register
    @RegisterBlock(offset: 0x18)
    public var txcrcr: Register<TXCRCR>

    /// SPI_I2S configuration register
    @RegisterBlock(offset: 0x1c)
    public var i2scfgr: Register<I2SCFGR>

    /// SPI_I2S prescaler register
    @RegisterBlock(offset: 0x20)
    public var i2spr: Register<I2SPR>

    /// Direct 8-bit access to data register
    @RegisterBlock(offset: 0xc)
    public var dr8: Register<DR8>
}

extension SPI {
    /// SPI control register 1
    @Register(bitWidth: 16)
    public struct CR1 {
        /// This bit is not used in I2S mode and SPI TI mode except the case when CRC is applied at TI mode.
        @ReadWrite(bits: 0..<1)
        public var cpha: CPHA

        /// This bit is not used in I2S mode and SPI TI mode except the case when CRC is applied at TI mode.
        @ReadWrite(bits: 1..<2)
        public var cpol: CPOL

        /// This bit is not used in I2S mode.
        @ReadWrite(bits: 2..<3)
        public var mstr: MSTR

        /// These bits are not used in I2S mode.
        @ReadWrite(bits: 3..<6)
        public var br: BR

        /// This bit is not used in I2S mode.
        @ReadWrite(bits: 6..<7)
        public var spe: SPE

        /// 2. This bit is not used in I2S mode and SPI TI mode.
        @ReadWrite(bits: 7..<8)
        public var lsbfirst: LSBFIRST

        /// Note: This bit is not used in I2S mode and SPI TI mode.
        @ReadWrite(bits: 8..<9)
        public var ssi: SSI

        /// Note: This bit is not used in I2S mode and SPI TI mode.
        @ReadWrite(bits: 9..<10)
        public var ssm: SSM

        /// Note: This bit is not used in I2S mode.
        @ReadWrite(bits: 10..<11)
        public var rxonly: RXONLY

        /// This bit is not used in I2S mode.
        @ReadWrite(bits: 11..<12)
        public var crcl: CRCL

        /// This bit is not used in I2S mode.
        @ReadWrite(bits: 12..<13)
        public var crcnext: CRCNEXT

        /// This bit is not used in I2S mode.
        @ReadWrite(bits: 13..<14)
        public var crcen: CRCEN

        /// This bit is not used in I2S mode.
        @ReadWrite(bits: 14..<15)
        public var bidioe: BIDIOE

        /// Note: This bit is not used in I2S mode.
        @ReadWrite(bits: 15..<16)
        public var bidimode: BIDIMODE
    }

    /// SPI control register 2
    @Register(bitWidth: 16)
    public struct CR2 {
        /// When this bit is set, a DMA request is generated whenever the RXNE flag is set.
        @ReadWrite(bits: 0..<1)
        public var rxdmaen: RXDMAEN

        /// When this bit is set, a DMA request is generated whenever the TXE flag is set.
        @ReadWrite(bits: 1..<2)
        public var txdmaen: TXDMAEN

        /// Note: This bit is not used in I2S mode and SPI TI mode.
        @ReadWrite(bits: 2..<3)
        public var ssoe: SSOE

        /// 2. This bit is not used in I2S mode and SPI TI mode.
        @ReadWrite(bits: 3..<4)
        public var nssp: NSSP

        /// This bit is not used in I2S mode.
        @ReadWrite(bits: 4..<5)
        public var frf: FRF

        /// This bit controls the generation of an interrupt when an error condition occurs (CRCERR, OVR, MODF in SPI mode, FRE at TI mode and UDR, OVR, and FRE in I2S mode).
        @ReadWrite(bits: 5..<6)
        public var errie: ERRIE

        /// RX buffer not empty interrupt enable
        @ReadWrite(bits: 6..<7)
        public var rxneie: RXNEIE

        /// Tx buffer empty interrupt enable
        @ReadWrite(bits: 7..<8)
        public var txeie: TXEIE

        /// Note: These bits are not used in I2S mode.
        @ReadWrite(bits: 8..<12)
        public var ds: DS

        /// Note: This bit is not used in I2S mode.
        @ReadWrite(bits: 12..<13)
        public var frxth: FRXTH

        /// This bit is not used in I�S mode.
        @ReadWrite(bits: 13..<14)
        public var ldma_rx: LDMA_RX

        /// This bit is not used in I�S mode.
        @ReadWrite(bits: 14..<15)
        public var ldma_tx: LDMA_TX
    }

    /// SPI status register
    @Register(bitWidth: 16)
    public struct SR {
        /// Receive buffer not empty
        @ReadOnly(bits: 0..<1)
        public var rxne: RXNE

        /// Transmit buffer empty
        @ReadOnly(bits: 1..<2)
        public var txe: TXE

        /// Note: This bit is not used in SPI mode. It has no significance in PCM mode.
        @ReadOnly(bits: 2..<3)
        public var chside: CHSIDE

        /// Note: This bit is not used in SPI mode.
        @ReadOnly(bits: 3..<4)
        public var udr: UDR

        /// This bit is not used in I2S mode.
        @ReadWrite(bits: 4..<5)
        public var crcerr: CRCERR

        /// Note: This bit is not used in I2S mode.
        @ReadOnly(bits: 5..<6)
        public var modf: MODF

        /// This flag is set by hardware and reset by a software sequence. Refer to page 1385 for the software sequence.
        @ReadOnly(bits: 6..<7)
        public var ovr: OVR

        /// Note: The BSY flag must be used with caution: refer to and .
        @ReadOnly(bits: 7..<8)
        public var bsy: BSY

        /// This flag is set by hardware and reset when SPI_SR is read by software.
        @ReadOnly(bits: 8..<9)
        public var fre: FRE

        /// Note: These bits are not used in I�S mode and in SPI receive-only mode while CRC calculation is enabled.
        @ReadOnly(bits: 9..<11)
        public var frlvl: FRLVL

        /// Note: This bit is not used in I2S mode.
        @ReadOnly(bits: 11..<13)
        public var ftlvl: FTLVL
    }

    /// SPI data register
    @Register(bitWidth: 16)
    public struct DR {
        /// Note: Data is always right-aligned. Unused bits are ignored when writing to the register, and read as zero when the register is read. The Rx threshold setting must always correspond with the read access currently used.
        @ReadWrite(bits: 0..<16)
        public var dr_field: DR_FIELD
    }

    /// SPI CRC polynomial register
    @Register(bitWidth: 16)
    public struct CRCPR {
        /// The CRC polynomial (0x0007) is the reset value of this register. Another polynomial can be configured as required.
        @ReadWrite(bits: 0..<16)
        public var crcpoly: CRCPOLY
    }

    /// SPI Rx CRC register
    @Register(bitWidth: 16)
    public struct RXCRCR {
        /// These bits are not used in I2S mode.
        @ReadOnly(bits: 0..<16)
        public var rxcrc: RXCRC
    }

    /// SPI Tx CRC register
    @Register(bitWidth: 16)
    public struct TXCRCR {
        /// These bits are not used in I2S mode.
        @ReadOnly(bits: 0..<16)
        public var txcrc: TXCRC
    }

    /// SPI_I2S configuration register
    @Register(bitWidth: 16)
    public struct I2SCFGR {
        /// It is not used in SPI mode.
        @ReadWrite(bits: 0..<1)
        public var chlen: CHLEN

        /// They are not used in SPI mode.
        @ReadWrite(bits: 1..<3)
        public var datlen: DATLEN

        /// The bit CKPOL does not affect the CK edge sensitivity used to receive or transmit the SD and WS signals.
        @ReadWrite(bits: 3..<4)
        public var ckpol: CKPOL

        /// They are not used in SPI mode.
        @ReadWrite(bits: 4..<6)
        public var i2sstd: I2SSTD

        /// It is not used in SPI mode.
        @ReadWrite(bits: 7..<8)
        public var pcmsync: PCMSYNC

        /// They are not used in SPI mode.
        @ReadWrite(bits: 8..<10)
        public var i2scfg: I2SCFG

        /// Note: This bit is not used in SPI mode.
        @ReadWrite(bits: 10..<11)
        public var i2se: I2SE

        /// Note: This bit should be configured when the SPI is disabled.
        @ReadWrite(bits: 11..<12)
        public var i2smod: I2SMOD

        /// Please refer to for additional information.
        @ReadWrite(bits: 12..<13)
        public var astrten: ASTRTEN
    }

    /// SPI_I2S prescaler register
    @Register(bitWidth: 16)
    public struct I2SPR {
        /// They are not used in SPI mode.
        @ReadWrite(bits: 0..<8)
        public var i2sdiv: I2SDIV

        /// It is not used in SPI mode.
        @ReadWrite(bits: 8..<9)
        public var odd: ODD

        /// It is not used in SPI mode.
        @ReadWrite(bits: 9..<10)
        public var mckoe: MCKOE
    }

    /// Direct 8-bit access to data register
    @Register(bitWidth: 8)
    public struct DR8 {
        /// Data register
        @ReadWrite(bits: 0..<8)
        public var dr: DR
    }
}
