// Generated by svd2swift.

import MMIO

/// General-purpose timer
@RegisterBlock
public struct TIM3: Sendable {
    /// TIM3 control register 1
    @RegisterBlock(offset: 0x0)
    public var cr1: Register<CR1>

    /// TIM3 control register 2
    @RegisterBlock(offset: 0x4)
    public var cr2: Register<CR2>

    /// TIM3 slave mode control register
    @RegisterBlock(offset: 0x8)
    public var smcr: Register<SMCR>

    /// TIM3 DMA/Interrupt enable register
    @RegisterBlock(offset: 0xc)
    public var dier: Register<DIER>

    /// TIM3 status register
    @RegisterBlock(offset: 0x10)
    public var sr: Register<SR>

    /// TIM3 event generation register
    @RegisterBlock(offset: 0x14)
    public var egr: Register<EGR>

    /// TIM3 capture/compare mode register 1 [alternate]
    @RegisterBlock(offset: 0x18)
    public var ccmr1_input: Register<CCMR1_input>

    /// TIM3 capture/compare mode register 1 [alternate]
    @RegisterBlock(offset: 0x18)
    public var ccmr1_output: Register<CCMR1_output>

    /// TIM3 capture/compare mode register 2 [alternate]
    @RegisterBlock(offset: 0x1c)
    public var ccmr2_input: Register<CCMR2_input>

    /// TIM3 capture/compare mode register 2 [alternate]
    @RegisterBlock(offset: 0x1c)
    public var ccmr2_output: Register<CCMR2_output>

    /// TIM3 capture/compare enable register
    @RegisterBlock(offset: 0x20)
    public var ccer: Register<CCER>

    /// TIM3 counter [alternate]
    @RegisterBlock(offset: 0x24)
    public var cnt: Register<CNT>

    /// TIM3 prescaler
    @RegisterBlock(offset: 0x28)
    public var psc: Register<PSC>

    /// TIM3 auto-reload register
    @RegisterBlock(offset: 0x2c)
    public var arr: Register<ARR>

    /// TIM3 capture/compare register 1
    @RegisterBlock(offset: 0x34)
    public var ccr1: Register<CCR1>

    /// TIM3 capture/compare register 2
    @RegisterBlock(offset: 0x38)
    public var ccr2: Register<CCR2>

    /// TIM3 capture/compare register 3
    @RegisterBlock(offset: 0x3c)
    public var ccr3: Register<CCR3>

    /// TIM3 capture/compare register 4
    @RegisterBlock(offset: 0x40)
    public var ccr4: Register<CCR4>

    /// TIM3 DMA control register
    @RegisterBlock(offset: 0x48)
    public var dcr: Register<DCR>

    /// TIM3 DMA address for full transfer
    @RegisterBlock(offset: 0x4c)
    public var dmar: Register<DMAR>

    /// TIM3 alternate function option register 1
    @RegisterBlock(offset: 0x60)
    public var af1: Register<AF1>

    /// TIM3 timer input selection register
    @RegisterBlock(offset: 0x68)
    public var tisel: Register<TISEL>
}

extension TIM3 {
    /// TIM3 control register 1
    @Register(bitWidth: 16)
    public struct CR1 {
        /// CEN is cleared automatically in one-pulse mode, when an update event occurs.
        @ReadWrite(bits: 0..<1)
        public var cen: CEN

        /// Buffered registers are then loaded with their preload values.
        @ReadWrite(bits: 1..<2)
        public var udis: UDIS

        /// Update generation through the slave mode controller
        @ReadWrite(bits: 2..<3)
        public var urs: URS

        /// One-pulse mode
        @ReadWrite(bits: 3..<4)
        public var opm: OPM

        /// Note: This bit is read only when the timer is configured in Center-aligned mode or Encoder mode.
        @ReadWrite(bits: 4..<5)
        public var dir: DIR

        /// Note: It is not allowed to switch from edge-aligned mode to center-aligned mode as long as the counter is enabled (CEN=1)
        @ReadWrite(bits: 5..<7)
        public var cms: CMS

        /// Auto-reload preload enable
        @ReadWrite(bits: 7..<8)
        public var arpe: ARPE

        /// This bit-field indicates the division ratio between the timer clock (CK_INT) frequency and sampling clock used by the digital filters (ETR, TIx),
        @ReadWrite(bits: 8..<10)
        public var ckd: CKD

        /// UIF status bit remapping
        @ReadWrite(bits: 11..<12)
        public var uifremap: UIFREMAP
    }

    /// TIM3 control register 2
    @Register(bitWidth: 16)
    public struct CR2 {
        /// Capture/compare DMA selection
        @ReadWrite(bits: 3..<4)
        public var ccds: CCDS

        /// Note: The clock of the slave timer or ADC must be enabled prior to receive events from the master timer, and must not be changed on-the-fly while triggers are received from the master timer.
        @ReadWrite(bits: 4..<7)
        public var mms: MMS

        /// TI1 selection
        @ReadWrite(bits: 7..<8)
        public var ti1s: TI1S
    }

    /// TIM3 slave mode control register
    @Register(bitWidth: 32)
    public struct SMCR {
        /// Note: The clock of the slave peripherals (timer, ADC, ...) receiving the TRGO or the TRGO2 signals must be enabled prior to receive events from the master timer, and the clock frequency (prescaler) must not be changed on-the-fly while triggers are received from the master timer.
        @ReadWrite(bits: 0..<3)
        public var sms1: SMS1

        /// This bit is used to select the OCREF clear source
        @ReadWrite(bits: 3..<4)
        public var occs: OCCS

        /// Note: These bits must be changed only when they are not used (e.g. when SMS=000) to avoid wrong edge detections at the transition.
        @ReadWrite(bits: 4..<7)
        public var ts1: TS1

        /// Master/Slave mode
        @ReadWrite(bits: 7..<8)
        public var msm: MSM

        /// This bit-field then defines the frequency used to sample ETRP signal and the length of the digital filter applied to ETRP. The digital filter is made of an event counter in which N consecutive events are needed to validate a transition on the output:
        @ReadWrite(bits: 8..<12)
        public var etf: ETF

        /// External trigger signal ETRP frequency must be at most 1/4 of CK_INT frequency. A prescaler can be enabled to reduce ETRP frequency. It is useful when inputting fast external clocks.
        @ReadWrite(bits: 12..<14)
        public var etps: ETPS

        /// If external clock mode 1 and external clock mode 2 are enabled at the same time, the external clock input is ETRF.
        @ReadWrite(bits: 14..<15)
        public var ece: ECE

        /// This bit selects whether ETR or ETR is used for trigger operations
        @ReadWrite(bits: 15..<16)
        public var etp: ETP

        /// Note: The clock of the slave peripherals (timer, ADC, ...) receiving the TRGO or the TRGO2 signals must be enabled prior to receive events from the master timer, and the clock frequency (prescaler) must not be changed on-the-fly while triggers are received from the master timer.
        @ReadWrite(bits: 16..<17)
        public var sms2: SMS2

        /// Note: These bits must be changed only when they are not used (e.g. when SMS=000) to avoid wrong edge detections at the transition.
        @ReadWrite(bits: 20..<22)
        public var ts2: TS2
    }

    /// TIM3 DMA/Interrupt enable register
    @Register(bitWidth: 16)
    public struct DIER {
        /// Update interrupt enable
        @ReadWrite(bits: 0..<1)
        public var uie: UIE

        /// Capture/Compare 1 interrupt enable
        @ReadWrite(bits: 1..<2)
        public var cc1ie: CC1IE

        /// Capture/Compare 2 interrupt enable
        @ReadWrite(bits: 2..<3)
        public var cc2ie: CC2IE

        /// Capture/Compare 3 interrupt enable
        @ReadWrite(bits: 3..<4)
        public var cc3ie: CC3IE

        /// Capture/Compare 4 interrupt enable
        @ReadWrite(bits: 4..<5)
        public var cc4ie: CC4IE

        /// Trigger interrupt enable
        @ReadWrite(bits: 6..<7)
        public var tie: TIE

        /// Update DMA request enable
        @ReadWrite(bits: 8..<9)
        public var ude: UDE

        /// Capture/Compare 1 DMA request enable
        @ReadWrite(bits: 9..<10)
        public var cc1de: CC1DE

        /// Capture/Compare 2 DMA request enable
        @ReadWrite(bits: 10..<11)
        public var cc2de: CC2DE

        /// Capture/Compare 3 DMA request enable
        @ReadWrite(bits: 11..<12)
        public var cc3de: CC3DE

        /// Capture/Compare 4 DMA request enable
        @ReadWrite(bits: 12..<13)
        public var cc4de: CC4DE

        /// Trigger DMA request enable
        @ReadWrite(bits: 14..<15)
        public var tde: TDE
    }

    /// TIM3 status register
    @Register(bitWidth: 16)
    public struct SR {
        /// When CNT is reinitialized by a trigger event (refer to the synchro control register description), if URS=0 and UDIS=0 in the TIMx_CR1 register.
        @ReadWrite(bits: 0..<1)
        public var uif: UIF

        /// If channel CC1 is configured as input: this bit is set when counter value has been captured in TIMx_CCR1 register (an edge has been detected on IC1, as per the edge sensitivity defined with the CC1P and CC1NP bits setting, in TIMx_CCER).
        @ReadWrite(bits: 1..<2)
        public var cc1if: CC1IF

        /// Refer to CC1IF description
        @ReadWrite(bits: 2..<3)
        public var cc2if: CC2IF

        /// Refer to CC1IF description
        @ReadWrite(bits: 3..<4)
        public var cc3if: CC3IF

        /// Refer to CC1IF description
        @ReadWrite(bits: 4..<5)
        public var cc4if: CC4IF

        /// This flag is set by hardware on the TRG trigger event (active edge detected on TRGI input when the slave mode controller is enabled in all modes but gated mode. It is set when the counter starts or stops when gated mode is selected. It is cleared by software.
        @ReadWrite(bits: 6..<7)
        public var tif: TIF

        /// This flag is set by hardware only when the corresponding channel is configured in input capture mode. It is cleared by software by writing it to ‘0’.
        @ReadWrite(bits: 9..<10)
        public var cc1of: CC1OF

        /// refer to CC1OF description
        @ReadWrite(bits: 10..<11)
        public var cc2of: CC2OF

        /// refer to CC1OF description
        @ReadWrite(bits: 11..<12)
        public var cc3of: CC3OF

        /// refer to CC1OF description
        @ReadWrite(bits: 12..<13)
        public var cc4of: CC4OF
    }

    /// TIM3 event generation register
    @Register(bitWidth: 16)
    public struct EGR {
        /// This bit can be set by software, it is automatically cleared by hardware.
        @WriteOnly(bits: 0..<1)
        public var ug: UG

        /// The current value of the counter is captured in TIMx_CCR1 register. The CC1IF flag is set, the corresponding interrupt or DMA request is sent if enabled. The CC1OF flag is set if the CC1IF flag was already high.
        @WriteOnly(bits: 1..<2)
        public var cc1g: CC1G

        /// Refer to CC1G description
        @WriteOnly(bits: 2..<3)
        public var cc2g: CC2G

        /// Refer to CC1G description
        @WriteOnly(bits: 3..<4)
        public var cc3g: CC3G

        /// Refer to CC1G description
        @WriteOnly(bits: 4..<5)
        public var cc4g: CC4G

        /// This bit is set by software in order to generate an event, it is automatically cleared by hardware.
        @WriteOnly(bits: 6..<7)
        public var tg: TG
    }

    /// TIM3 capture/compare mode register 1 [alternate]
    @Register(bitWidth: 32)
    public struct CCMR1_input {
        /// Note: CC1S bits are writable only when the channel is OFF (CC1E = 0 in TIMx_CCER).
        @ReadWrite(bits: 0..<2)
        public var cc1s: CC1S

        /// This bit-field defines the ratio of the prescaler acting on CC1 input (IC1). The prescaler is reset as soon as CC1E=0 (TIMx_CCER register).
        @ReadWrite(bits: 2..<4)
        public var ic1psc: IC1PSC

        /// This bit-field defines the frequency used to sample TI1 input and the length of the digital filter applied to TI1. The digital filter is made of an event counter in which N consecutive events are needed to validate a transition on the output:
        @ReadWrite(bits: 4..<8)
        public var ic1f: IC1F

        /// Note: CC2S bits are writable only when the channel is OFF (CC2E = 0 in TIMx_CCER).
        @ReadWrite(bits: 8..<10)
        public var cc2s: CC2S

        /// Input capture 2 prescaler
        @ReadWrite(bits: 10..<12)
        public var ic2psc: IC2PSC

        /// Input capture 2 filter
        @ReadWrite(bits: 12..<16)
        public var ic2f: IC2F
    }

    /// TIM3 capture/compare mode register 1 [alternate]
    @Register(bitWidth: 32)
    public struct CCMR1_output {
        /// Note: CC1S bits are writable only when the channel is OFF (CC1E = 0 in TIMx_CCER).
        @ReadWrite(bits: 0..<2)
        public var cc1s: CC1S

        /// This bit decreases the latency between a trigger event and a transition on the timer output. It must be used in one-pulse mode (OPM bit set in TIMx_CR1 register), to have the output pulse starting as soon as possible after the starting trigger.
        @ReadWrite(bits: 2..<3)
        public var oc1fe: OC1FE

        /// Note: The PWM mode can be used without validating the preload register only in one-pulse mode (OPM bit set in TIMx_CR1 register). Else the behavior is not guaranteed.
        @ReadWrite(bits: 3..<4)
        public var oc1pe: OC1PE

        /// Note: The OC1M[3] bit is not contiguous, located in bit 16.
        @ReadWrite(bits: 4..<7)
        public var oc1m1: OC1M1

        /// Output compare 1 clear enable
        @ReadWrite(bits: 7..<8)
        public var oc1ce: OC1CE

        /// Note: CC2S bits are writable only when the channel is OFF (CC2E = 0 in TIMx_CCER).
        @ReadWrite(bits: 8..<10)
        public var cc2s: CC2S

        /// Output compare 2 fast enable
        @ReadWrite(bits: 10..<11)
        public var oc2fe: OC2FE

        /// Output compare 2 preload enable
        @ReadWrite(bits: 11..<12)
        public var oc2pe: OC2PE

        /// refer to OC1M description on bits 6:4
        @ReadWrite(bits: 12..<15)
        public var oc2m1: OC2M1

        /// Output compare 2 clear enable
        @ReadWrite(bits: 15..<16)
        public var oc2ce: OC2CE

        /// Note: The OC1M[3] bit is not contiguous, located in bit 16.
        @ReadWrite(bits: 16..<17)
        public var oc1m2: OC1M2

        /// refer to OC1M description on bits 6:4
        @ReadWrite(bits: 24..<25)
        public var oc2m2: OC2M2
    }

    /// TIM3 capture/compare mode register 2 [alternate]
    @Register(bitWidth: 32)
    public struct CCMR2_input {
        /// Note: CC3S bits are writable only when the channel is OFF (CC3E = 0 in TIMx_CCER).
        @ReadWrite(bits: 0..<2)
        public var cc3s: CC3S

        /// Input capture 3 prescaler
        @ReadWrite(bits: 2..<4)
        public var ic3psc: IC3PSC

        /// Input capture 3 filter
        @ReadWrite(bits: 4..<8)
        public var ic3f: IC3F

        /// Note: CC4S bits are writable only when the channel is OFF (CC4E = 0 in TIMx_CCER).
        @ReadWrite(bits: 8..<10)
        public var cc4s: CC4S

        /// Input capture 4 prescaler
        @ReadWrite(bits: 10..<12)
        public var ic4psc: IC4PSC

        /// Input capture 4 filter
        @ReadWrite(bits: 12..<16)
        public var ic4f: IC4F
    }

    /// TIM3 capture/compare mode register 2 [alternate]
    @Register(bitWidth: 32)
    public struct CCMR2_output {
        /// Note: CC3S bits are writable only when the channel is OFF (CC3E = 0 in TIMx_CCER).
        @ReadWrite(bits: 0..<2)
        public var cc3s: CC3S

        /// Output compare 3 fast enable
        @ReadWrite(bits: 2..<3)
        public var oc3fe: OC3FE

        /// Output compare 3 preload enable
        @ReadWrite(bits: 3..<4)
        public var oc3pe: OC3PE

        /// Refer to OC1M description (bits 6:4 in TIMx_CCMR1 register)
        @ReadWrite(bits: 4..<7)
        public var oc3m1: OC3M1

        /// Output compare 3 clear enable
        @ReadWrite(bits: 7..<8)
        public var oc3ce: OC3CE

        /// Note: CC4S bits are writable only when the channel is OFF (CC4E = 0 in TIMx_CCER).
        @ReadWrite(bits: 8..<10)
        public var cc4s: CC4S

        /// Output compare 4 fast enable
        @ReadWrite(bits: 10..<11)
        public var oc4fe: OC4FE

        /// Output compare 4 preload enable
        @ReadWrite(bits: 11..<12)
        public var oc4pe: OC4PE

        /// Refer to OC1M description (bits 6:4 in TIMx_CCMR1 register)
        @ReadWrite(bits: 12..<15)
        public var oc4m1: OC4M1

        /// Output compare 4 clear enable
        @ReadWrite(bits: 15..<16)
        public var oc4ce: OC4CE

        /// Refer to OC1M description (bits 6:4 in TIMx_CCMR1 register)
        @ReadWrite(bits: 16..<17)
        public var oc3m2: OC3M2

        /// Refer to OC1M description (bits 6:4 in TIMx_CCMR1 register)
        @ReadWrite(bits: 24..<25)
        public var oc4m2: OC4M2
    }

    /// TIM3 capture/compare enable register
    @Register(bitWidth: 16)
    public struct CCER {
        /// Capture/Compare 1 output enable.
        @ReadWrite(bits: 0..<1)
        public var cc1e: CC1E

        /// CC1NP=1, CC1P=0:	This configuration is reserved, it must not be used.
        @ReadWrite(bits: 1..<2)
        public var cc1p: CC1P

        /// CC1 channel configured as input: This bit is used in conjunction with CC1P to define TI1FP1/TI2FP1 polarity. refer to CC1P description.
        @ReadWrite(bits: 3..<4)
        public var cc1np: CC1NP

        /// Refer to CC1E description
        @ReadWrite(bits: 4..<5)
        public var cc2e: CC2E

        /// refer to CC1P description
        @ReadWrite(bits: 5..<6)
        public var cc2p: CC2P

        /// Refer to CC1NP description
        @ReadWrite(bits: 7..<8)
        public var cc2np: CC2NP

        /// Refer to CC1E description
        @ReadWrite(bits: 8..<9)
        public var cc3e: CC3E

        /// Refer to CC1P description
        @ReadWrite(bits: 9..<10)
        public var cc3p: CC3P

        /// Refer to CC1NP description
        @ReadWrite(bits: 11..<12)
        public var cc3np: CC3NP

        /// refer to CC1E description
        @ReadWrite(bits: 12..<13)
        public var cc4e: CC4E

        /// Refer to CC1P description
        @ReadWrite(bits: 13..<14)
        public var cc4p: CC4P

        /// Refer to CC1NP description
        @ReadWrite(bits: 15..<16)
        public var cc4np: CC4NP
    }

    /// TIM3 counter [alternate]
    @Register(bitWidth: 32)
    public struct CNT {
        /// counter value
        @ReadWrite(bits: 0..<16)
        public var cnt_field: CNT_FIELD

        /// This bit is a read-only copy of the UIF bit of the TIMx_ISR register
        @ReadWrite(bits: 31..<32)
        public var uifcpy: UIFCPY
    }

    /// TIM3 prescaler
    @Register(bitWidth: 16)
    public struct PSC {
        /// PSC contains the value to be loaded in the active prescaler register at each update event (including when the counter is cleared through UG bit of TIMx_EGR register or through trigger controller when configured in “reset mode”).
        @ReadWrite(bits: 0..<16)
        public var psc_field: PSC_FIELD
    }

    /// TIM3 auto-reload register
    @Register(bitWidth: 32)
    public struct ARR {
        /// The counter is blocked while the auto-reload value is null.
        @ReadWrite(bits: 0..<16)
        public var arr_field: ARR_FIELD
    }

    /// TIM3 capture/compare register 1
    @Register(bitWidth: 32)
    public struct CCR1 {
        /// CCR1 is the counter value transferred by the last input capture 1 event (IC1). The TIMx_CCR1 register is read-only and cannot be programmed.
        @ReadWrite(bits: 0..<16)
        public var ccr1_field: CCR1_FIELD
    }

    /// TIM3 capture/compare register 2
    @Register(bitWidth: 32)
    public struct CCR2 {
        /// CCR2 is the counter value transferred by the last input capture 2 event (IC2). The TIMx_CCR2 register is read-only and cannot be programmed.
        @ReadWrite(bits: 0..<16)
        public var ccr2_field: CCR2_FIELD
    }

    /// TIM3 capture/compare register 3
    @Register(bitWidth: 32)
    public struct CCR3 {
        /// CCR3 is the counter value transferred by the last input capture 3 event (IC3). The TIMx_CCR3 register is read-only and cannot be programmed.
        @ReadWrite(bits: 0..<16)
        public var ccr3_field: CCR3_FIELD
    }

    /// TIM3 capture/compare register 4
    @Register(bitWidth: 32)
    public struct CCR4 {
        /// CCR4 is the counter value transferred by the last input capture 4 event (IC4). The TIMx_CCR4 register is read-only and cannot be programmed.
        @ReadWrite(bits: 0..<16)
        public var ccr4_field: CCR4_FIELD
    }

    /// TIM3 DMA control register
    @Register(bitWidth: 16)
    public struct DCR {
        /// DBA = TIMx_CR1. In this case the transfer is done to/from 7 registers starting from the TIMx_CR1 address.
        @ReadWrite(bits: 0..<5)
        public var dba: DBA

        /// ...
        @ReadWrite(bits: 8..<13)
        public var dbl: DBL
    }

    /// TIM3 DMA address for full transfer
    @Register(bitWidth: 16)
    public struct DMAR {
        /// where TIMx_CR1 address is the address of the control register 1, DBA is the DMA base address configured in TIMx_DCR register, DMA index is automatically controlled by the DMA transfer, and ranges from 0 to DBL (DBL configured in TIMx_DCR).
        @ReadWrite(bits: 0..<16)
        public var dmab: DMAB
    }

    /// TIM3 alternate function option register 1
    @Register(bitWidth: 32)
    public struct AF1 {
        /// Others: Reserved
        @ReadWrite(bits: 14..<18)
        public var etrsel: ETRSEL
    }

    /// TIM3 timer input selection register
    @Register(bitWidth: 32)
    public struct TISEL {
        /// Others: Reserved
        @ReadWrite(bits: 0..<4)
        public var ti1sel: TI1SEL

        /// Others: Reserved
        @ReadWrite(bits: 8..<12)
        public var ti2sel: TI2SEL

        /// Others: Reserved
        @ReadWrite(bits: 16..<20)
        public var ti3sel: TI3SEL
    }
}
